name: Trigger QA Build on PR Merge

on:
    push:
        branches:
            - main

jobs:
    trigger:
        name: Dispatch QA build
        runs-on: ubuntu-latest
        steps:
            - name: Dispatch to infra repo
              uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
              with:
                  github-token: ${{ secrets.GH_TOKEN }}
                  script: |
                      await github.rest.repos.createDispatchEvent({
                        owner: 'theolecuyer',
                        repo: 'detailsnap-web-infra',
                        event_type: 'qa-build',
                      });
                      console.log('Dispatched QA build for commit: ${{ github.sha }}');
